name: Metrics

on:
  schedule: [{ cron: '15 */8 * * *' }]
  workflow_dispatch:
  push: { branches: ['main'] }

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: General overview
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.general.overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

      - name: Full-year calendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

      - name: Indepth analysis
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

      - name: Recent activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

      - name: Full history calendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_calendar: yes
          plugin_calendar_limit: 0
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

      - name: Comment reactions
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
